# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

require 'google/protobuf'


descriptor_data = "\n\rMessage.proto\x12\x0f\x63om.hasup.proto\"\xab\x01\n\x07Message\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.com.hasup.proto.Message.Type\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"<\n\x04Type\x12\r\n\tSUBSCRIBE\x10\x00\x12\x0f\n\x0bUNSUBSCRIBE\x10\x01\x12\n\n\x06STATUS\x10\x02\x12\x08\n\x04SYNC\x10\x03\x42\'\n\x0f\x63om.hasup.protoB\x0cMessageProto\xea\x02\x05Hasupb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hasup
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Message").msgclass
  Message::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.hasup.proto.Message.Type").enummodule
end
